// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/activities": {
    params: {};
  };
  "/goals": {
    params: {};
  };
  "/workouts": {
    params: {};
  };
  "/user-profile": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signup" | "/dashboard" | "/profile" | "/settings" | "/activities" | "/goals" | "/workouts" | "/user-profile" | "/*";
  };
  "./components/home/LandingPage.tsx": {
    id: "components/home/LandingPage";
    page: "/";
  };
  "./components/signup/SignInScreen.tsx": {
    id: "components/signup/SignInScreen";
    page: "/signup";
  };
  "./components/dashboard/Mydash.tsx": {
    id: "components/dashboard/Mydash";
    page: "/dashboard";
  };
  "./components/profile/MyProfile.tsx": {
    id: "components/profile/MyProfile";
    page: "/profile";
  };
  "./components/settings/Mysettings.tsx": {
    id: "components/settings/Mysettings";
    page: "/settings";
  };
  "./components/myactivity/MyActivity.tsx": {
    id: "components/myactivity/MyActivity";
    page: "/activities";
  };
  "./components/goals/Goals.tsx": {
    id: "components/goals/Goals";
    page: "/goals";
  };
  "./components/workouts/Workouts.tsx": {
    id: "components/workouts/Workouts";
    page: "/workouts";
  };
  "./components/profile/Myprofile.tsx": {
    id: "components/profile/Myprofile";
    page: "/user-profile";
  };
  "catchall.tsx": {
    id: "catchall";
    page: "/" | "/*";
  };
};